# Generated by Django 6.0.6 on 2026-06-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('solar_status', models.CharField(choices=[('unknown', 'Unknown'), ('has_solar', 'Has Solar'), ('no_solar', 'No Solar'), ('error', 'Error')], default='unknown', max_length=20)),
                ('solar_confidence', models.FloatField(blank=True, null=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sold_date'],
            },
        ),
    ]
