# Generated by Django 6.0.6 on 2026-06-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='scan_detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='stages_triggered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
